@startuml
left to right direction

actor Клиент
actor Кассир
actor Мойщик
actor Директор

rectangle "Система Автомойка" {
  (Зарегистрироваться по номеру телефона) as UC001
  (Добавление, редактирование информации об автомобилях) as UC002
  (Просмотр каталога автомоек) as UC003
  (Просмотр услуг и цен) as UC004
  (Просмотр реальной загрузки автомоек) as UC005
  (Онлайн-запись) as UC006
  (История всех заказов) as UC007
  (Гибкая отмена и перенос записи) as UC008
  (Просмотр персональных предложений и скидок) as UC025
  
  (Быстрая регистрация новых клиентов) as UC009
  (Поиск и редактирование существующих клиентов) as UC010
  (Просмотр и управление текущими записями) as UC011
  (Прием оплаты за услуги) as UC012
  (Просмотр истории платежей) as UC013
  
  (Просмотр рабочего расписания) as UC014
  (Информация о каждом автомобиле и пожеланиях клиента) as UC015
  (Фиксация начала и окончания мойки) as UC016
  (Обзор истории выполненных работ) as UC017
  (Просмотр оценок и отзывов) as UC024
  
  (Добавление и редактирование данных об автомойках) as UC018
  (Формирование и корректировка прайс-листа) as UC019
  (Отчеты по финансовым показателям) as UC020
  (Отчеты по деятельности персонала) as UC021
  (Мониторинг популярности услуг) as UC022
  (Просмотр и анализ обратной связи от клиентов) as UC023
}

Клиент --> UC001
Клиент --> UC002
Клиент --> UC003
Клиент --> UC004
Клиент --> UC005
Клиент --> UC006
Клиент --> UC007
Клиент --> UC008
Клиент --> UC025

Кассир --> UC009
Кассир --> UC010
Кассир --> UC011
Кассир --> UC012
Кассир --> UC013

Мойщик --> UC014
Мойщик --> UC015
Мойщик --> UC016
Мойщик --> UC017
Мойщик --> UC024

Директор --> UC018
Директор --> UC019
Директор --> UC020
Директор --> UC021
Директор --> UC022
Директор --> UC023

@enduml